import assert from "node:assert/strict";
import test from "node:test";
import { chooseMotion } from "../lib/motion.ts";
import { stableJson, validateRecord, escapeXml } from "../lib/publication.ts";
import { records, publishedRecords, getVersion } from "../lib/records.ts";
import { readFile } from "node:fs/promises";
test("motion chooses one visible owner and holds it across minor area changes",()=>{const a={id:"a",visible:.9,area:90};const b={id:"b",visible:.8,area:100};assert.equal(chooseMotion([a,b],"a",false,false),"a");assert.equal(chooseMotion([{...a,area:20},b],"a",false,false),"b");});
test("paused and hidden pages stop automatic motion; manual play is scoped",()=>{const a={id:"a",visible:1,area:500};const b={id:"b",visible:.6,area:300,manual:true};assert.equal(chooseMotion([a],"a",true,false),null);assert.equal(chooseMotion([a,b],null,true,false),"b");assert.equal(chooseMotion([a,b],"b",false,true),null);assert.equal(chooseMotion([{...b,visible:.2}],"b",true,false),null);});
test("draft records never enter public feeds or resolve to invented versions",()=>{assert.ok(records.length>=11);for(const r of publishedRecords()){assert.equal(r.publication,"published");assert.ok(r.published);}assert.equal(getVersion("N-OPERATOR","1.0"),undefined);for(const r of records)validateRecord(r);});
test("every related record and identifier resolves uniquely",()=>{assert.equal(new Set(records.map(r=>r.id)).size,records.length);assert.equal(new Set(records.map(r=>r.slug)).size,records.length);for(const r of records)for(const id of r.related)assert.ok(records.some(r=>r.id===id),`${r.id} -> ${id}`);});
test("canonical hashing ignores object key order, but preserves semantic array order",()=>{assert.equal(stableJson({b:2,a:1}),stableJson({a:1,b:2}));assert.notEqual(stableJson([1,2]),stableJson([2,1]));assert.equal(stableJson({a:undefined,b:2}),'{"b":2}');});
test("publication requires a real date and XML text cannot create markup",()=>{assert.throws(()=>validateRecord({...records[0],publication:"published",published:undefined}),/date/);assert.equal(escapeXml('<title>&"'),"&lt;title&gt;&amp;&quot;");});
test("homepage contains every production scene without invented E25 results",async()=>{const page=await readFile(new URL("../app/page.tsx",import.meta.url),"utf8");assert.deepEqual([...page.matchAll(/data-scene="(\d+)"/g)].map(m=>m[1]),Array.from({length:14},(_,i)=>String(i).padStart(2,"0")));assert.doesNotMatch(page,/SUPPORTED.*NATURAL DEPTH|FINDING.*E25/);});

// Retrieval must not turn metadata associations into transcript-backed assertions.
const {channelVideos,allVideos,ibm,ibmVideos,latestMoe,popularMoe,videoReferences,getVideo,filterVideos,transcriptFor}=await import("../lib/youtube.ts");
const {recordGraph,searchGraph}=await import("../lib/graph.ts");
test("full channel catalogue preserves identity, unknown dates and source coverage",()=>{assert.equal(channelVideos.length,195);assert.equal(channelVideos.filter(v=>v.format==="short").length,18);assert.equal(new Set(channelVideos.map(v=>v.id)).size,195);assert.ok(channelVideos.some(v=>v.published===null));for(const v of channelVideos){assert.match(v.youtubeId,/^[A-Za-z0-9_-]{11}$/);assert.equal(v.url,`https://www.youtube.com/watch?v=${v.youtubeId}`);assert.match(v.sourceHash,/^[a-f0-9]{64}$/);if(v.viewsApproximate)assert.equal(v.metadataLevel,"listing");}});
test("archive filtering and popularity operate on real catalogue fields",()=>{assert.equal(filterVideos("","short").length,18);assert.equal(filterVideos("no-video-has-this-title").length,0);assert.ok(filterVideos("MCP").every(v=>`${v.title} ${v.description}`.toLowerCase().includes("mcp")));const top=filterVideos("","all","views");assert.ok(top.every((v,i)=>i===0||(top[i-1].views??-1)>=(v.views??-1)));});
test("graph edges resolve and timestamped retrieval cites the original source",()=>{const g=recordGraph();const ids=new Set(g.nodes.map(n=>(n as {id:string}).id));assert.equal(ids.size,g.nodes.length);for(const e of g.edges as {from:string;to:string}[]){assert.ok(ids.has(e.from),e.from);assert.ok(ids.has(e.to),e.to);}assert.equal(g.coverage.films,allVideos.length);assert.equal(g.coverage.transcripts,2);const results=searchGraph("graph");assert.ok(results.some(r=>r.basis==="automatic-caption"));for(const r of results.filter(r=>r.start!==undefined))assert.ok(r.sourceUrl.endsWith(`&t=${Math.floor(r.start!)}`));assert.equal(searchGraph("zzznomatchingcontentzzz").length,0);assert.ok(searchGraph("What has Chris said about models as databases?").length>0);});
test("transcript times stay within their source film and automatic provenance remains explicit",()=>{for(const v of channelVideos){const t=transcriptFor(v.youtubeId);if(!t)continue;assert.equal(t.status,"automatic-unreviewed");let end=-1;for(const p of t.passages){assert.ok(p.start>=end);assert.ok(p.end>=p.start);assert.ok(p.start<(v.duration||Infinity));assert.ok(p.text.trim());end=p.start;}}assert.equal(transcriptFor(getVideo("5_ZiJpl4hvs")!.youtubeId),undefined);});
test("full film players require explicit activation even when automatic motion is allowed",()=>{const player={id:"player",visible:1,area:1000,manualOnly:true};assert.equal(chooseMotion([player],null,false,false),null);assert.equal(chooseMotion([{...player,manual:true}],null,false,false),"player");assert.equal(chooseMotion([{...player,manual:true}],"player",false,true),null);});

test("IBM selections use source dates and counts, with separate producer and participant attribution",()=>{
 assert.equal(latestMoe.episode,"123");assert.equal(latestMoe.published,"2026-09-04");assert.equal(popularMoe.youtubeId,ibm.playlistMostViewedId);assert.equal(popularMoe.episode,"40");assert.ok(popularMoe.views!>latestMoe.views!);
 const edges=recordGraph().edges as {from:string;to:string;kind:string}[];
 for(const v of ibmVideos){assert.equal(v.producer,"IBM");assert.ok(v.participants?.includes("Chris Hay"));assert.ok(v.participationEvidence);assert.ok(v.published);assert.equal(v.viewsApproximate,false);assert.ok(edges.some(e=>e.from===v.id&&e.to==="ORG-IBM"&&e.kind==="created-by"));assert.ok(edges.some(e=>e.from===v.id&&e.to==="PERSON-CHRIS"&&e.kind==="features"));assert.ok(!edges.some(e=>e.from===v.id&&e.to==="PERSON-CHRIS"&&e.kind==="created-by"));const cite=JSON.parse(videoReferences(v).find(f=>f.id==="csl-json")!.text);assert.deepEqual(cite.author,[{literal:"IBM"}]);assert.ok(!channelVideos.some(c=>c.id===v.id));}
 assert.ok(searchGraph("agent security").some(r=>r.id===latestMoe.id));
});
