import Link from "next/link";
import { pageMetadata } from "@/lib/metadata";
import { recordGraph } from "@/lib/graph";
import { records, recordPath } from "@/lib/records";
export const metadata=pageMetadata("The connected record","Explore the systems, notebook, questions, films and source relationships behind Ask Chris Hay.","/knowledge");
export default function Page(){
 const graph=recordGraph();const c=graph.coverage;const concepts=graph.nodes.filter(n=>n.kind==="concept");
 return <main id="main" className="publication-main knowledge-page"><header className="index-intro"><p className="kicker record-voice">CHRIS HAY / THE CONNECTED RECORD</p><h1>One idea.<br/><em>Many connections.</em></h1><p className="dek">A system leads to a question. A notebook leads to a film. Each connection returns to a record.</p><p>The graph holds the text and the relationships behind Ask. An editorial connection and an association found in film metadata carry different labels.</p><div className="inline-links"><Link href="/ask" className="text-link">ASK THE WORK ↗</Link><Link href="/record" className="text-link">BROWSE THE CATALOGUE ↗</Link></div></header>
 <section className="knowledge-coverage" aria-label="Graph coverage"><div><strong>{c.records}</strong><span>RECORDS</span></div><div><strong>{c.acts}</strong><span>AUTHORED PASSAGES</span></div><div><strong>{c.chapters}</strong><span>FILM CHAPTERS</span></div><div><strong>{c.relationships}</strong><span>RELATIONSHIPS</span></div></section>
 <section className="knowledge-editorial"><p className="kicker record-voice">SYSTEMS / NOTEBOOK / QUESTIONS</p>{records.filter(r=>!r.youtubeId&&r.kind!=="film").map(r=><article key={r.id}><div><p className="record-voice">{r.id} · {r.publication.toUpperCase()} · {r.status}</p><h2><Link href={recordPath(r)}>{r.title} ↗</Link></h2><p>{r.abstract}</p></div><div className="knowledge-links"><p className="record-voice">EDITORIAL CONNECTIONS</p>{r.related.map(id=>records.find(x=>x.id===id)).filter(r=>r!==undefined).map(related=><Link href={recordPath(related)} key={related.id}>{related.title} ↗</Link>)}<Link className="text-link" href={`/ask?q=${encodeURIComponent(r.title)}`}>FIND IN THE RECORD ↗</Link></div></article>)}</section>
 <section className="knowledge-limits"><h2>What the sources contain.</h2><p>{c.films} films have catalogue records. {c.chapters} chapters identify topics and starting times; {c.transcripts} films have indexed automatic transcripts containing {c.passages} passages. A chapter title is not a transcript or proof of a claim.</p><p>{c.editorialDrafts} editorial records remain drafts. Their text is searchable with that status intact and can be excluded in Ask. Source references identify cited material; linked websites have not been imported in full.</p><a className="text-link" href="/api/graph">MACHINE-READABLE GRAPH ↗</a></section>
 <section className="knowledge-concepts"><p className="kicker record-voice">CONCEPTS / DISCOVERY ASSOCIATIONS</p>{concepts.map(concept=>{const ids=new Set(graph.edges.filter(e=>e.to===concept.id&&e.kind==="about").map(e=>e.from));const associated=records.filter(r=>ids.has(r.id));return <article key={concept.id} id={`concept-${concept.id.slice(8)}`}><h2>{concept.title}</h2><p>{concept.text}</p><div>{associated.slice(0,6).map(r=><Link href={recordPath(r)} key={r.id}>{r.title} ↗ <span className="record-voice">{r.publication === "draft"?"DRAFT":"SOURCE FILM"}</span></Link>)}</div><Link className="text-link" href={`/record?q=${encodeURIComponent(concept.id.slice(8))}`}>ALL {associated.length} ASSOCIATED RECORDS ↗</Link></article>;})}</section>
 </main>;
}
