import { pageMetadata } from "@/lib/metadata";
import { JsonLd } from "@chrishayuk/hause/components/JsonLd";
import { SITE } from "@/lib/records";
import type { Metadata } from "next";
import { notFound } from "next/navigation";
import Link from "next/link";
import { Media } from "@/components/Media";
import { SystemStudy } from "@/components/SystemStudy";
import { HauseStudy } from "@/components/HauseStudy";
import { FilmIndex } from "@/components/FilmIndex";
import { records, recordPath, sectionFor, socials } from "@/lib/records";
import { media } from "@/lib/media";
const sections = ["work","film","notebook","research","about","colophon","accessibility"];
export async function generateMetadata({ params }: { params: Promise<{section:string}> }): Promise<Metadata> { const {section}=await params; return pageMetadata(section.charAt(0).toUpperCase()+section.slice(1),`Chris Hay’s ${section}: part of a film, photography and research record.`,`/${section}`); }
export default async function IndexPage({params}:{params:Promise<{section:string}>}) {
 const {section}=await params; if(!sections.includes(section)) notFound();
 if(section==="film") return <main id="main" className="publication-main"><FilmIndex/></main>;
 if(section==="about") return <main id="main"><JsonLd data={{"@context":"https://schema.org","@type":"ProfilePage",url:`${SITE}/about`,mainEntity:{"@id":`${SITE}/#person`}}}/><header className="index-intro"><p className="kicker record-voice">THE PERSON / THE PRACTICE</p><h1>Chris Hay.</h1><p className="dek">Technologist, Futurist and Disruptor.</p></header><div className="about-layout"><Media id="portrait-editorial"/><div className="about-copy"><h2>A life<br/><em>in questions.</em></h2><p>Research, engineering, film and design. Intelligent systems, their representations, and the interfaces around them.</p><p>This publication connects the work: software, conversations, open questions and the notebook entries that sit between them. The projects are parts of a larger record.</p><p>London.</p><div className="inline-links">{Object.entries(socials).map(([label,url])=><a key={label} href={url} className="text-link">{label} ↗</a>)}</div></div></div></main>;
 if(section==="colophon") return <main id="main" className="prose-page"><p className="kicker record-voice">PUBLICATION NOTES / 0.1</p><h1>The colophon.</h1><p>CHRISHAYUK is a research house: a film-and-photography publication connecting Chris Hay’s work, ideas and public conversations.</p><h2>The production edition</h2><p>This is the first public edition. Editorial records remain drafts until individually reviewed and published. The YouTube collection contains real films and selected studio excerpts. Further location films and notebook photographs are still to be placed; marked media frames are production slots, not photographs of Chris or his work. The homepage’s visual launch criteria have not yet been met.</p><h2>Composed with HAUSE</h2><p>Real HAUSE semantic forms render the record. The publication adds its own photographic sequences, responsive media and a shared motion coordinator. Fraunces, Inter and Geist Mono supply the editorial, text and record voices.</p><p><a href="https://hause.design/">The specimen book ↗</a></p><h2>Rights and sources</h2><p>Selected IBM episodes use their official YouTube players and posters. IBM remains the producer and host of the original footage; Chris appears as a participant. The collection leads with his latest verified appearance and the most-viewed episode in the official playlist snapshot. Earlier editorial appearance records remain available.</p><p>The typographic social image was generated for this publication. Research notes retain source descriptions and exact draft status. Illustrative E25 findings from the brief have not been published as experimental facts.</p><h2>The media register</h2><ul className="production-list">{media.map(m=><li key={m.id}>{m.title}<span>{m.state === "ready" ? "AVAILABLE" : "ORIGINAL REQUIRED"}</span></li>)}</ul><h2>Publishing the record</h2><p>Published records enter the feeds. The machine-readable index also includes source-attributed YouTube catalogue records. Draft references omit a publication date. Material revisions will retain their earlier snapshots and citations.</p><p><a href="/api/records">Public record index</a> · <a href="/rss.xml">RSS</a> · <a href="/feed.json">JSON Feed</a></p></main>;
 if(section==="accessibility") return <main id="main" className="prose-page"><p className="kicker record-voice">READING THE PUBLICATION</p><h1>At your pace.</h1><h2>Motion is optional</h2><p>Use the motion control in the header to pause automatic movement. Reduced-motion and supported reduced-data preferences start with still compositions. Sound never starts automatically.</p><h2>A readable record</h2><p>Headings, descriptions, notebook text and sources are server-rendered. The story does not require interpreting an animation. Keyboard navigation and explicit controls accompany interactive forms.</p><h2>Film and transcripts</h2><p>The current film selection links to IBM’s original episode pages, where the films and transcripts can be read or watched. Media rights determine whether a transcript can also be hosted here.</p><h2>Current review status</h2><p>This production edition has not completed a browser accessibility audit. The media shoot and final image contrast remain part of the ongoing production review.</p><Link href="/about" className="text-link">CONTACT CHRIS ↗</Link></main>;
 const entries=records.filter(r=>sectionFor(r)===section);
 const headings:Record<string,string>={work:"Work",notebook:"Notebook",research:"Research"};
 const descriptions:Record<string,string>={work:"Software, systems and the questions that make them necessary.",notebook:"Thoughts in progress. Room for an idea before it becomes an answer.",research:"Questions, observations and the boundary of what has been shown."};
 return <main id="main" className="publication-main"><header className="index-intro"><p className="kicker record-voice">THE RECORD / {section.toUpperCase()}</p><h1>{headings[section]}<span className="amber">.</span></h1><p className="dek">{descriptions[section]}</p><div className="index-count record-voice"><span>{String(entries.length).padStart(2,"0")} RECORDS</span><span>PRODUCTION EDITION / DRAFTS</span></div></header>{section==="work" ? <div className="work-index">{entries.map((r,i)=><article key={r.id} className="work-story"><Link href={recordPath(r)} className="work-story-heading"><h2>{r.title}</h2><span>↗</span></Link>{r.id==="W-VINDEX3" ? <SystemStudy/> : r.id==="W-HAUSE" ? <HauseStudy/> : <Media id={r.media[0]}/>}<p>{r.dek}</p><Link href={recordPath(r)} className="text-link">OPEN DOSSIER <span className="record-voice">0{i+1} ↗</span></Link></article>)}</div> : <div className="record-list">{entries.map(r=><Link key={r.id} href={recordPath(r)}><span className="record-voice">{r.id}<br/>{r.status}<br/>{r.created}</span><div><h2>{r.title}</h2><p>{r.dek}</p></div><span>↗</span></Link>)}</div>}</main>;
}
