import { HOUSE } from "@/lib/house";
import { MoeScene } from "@/components/MoeCollection";
import { FilmSelection, YouTubeScene } from "@/components/YouTubeCollection";
import Link from "next/link";
import { Media } from "@/components/Media";
import { SystemStudy } from "@/components/SystemStudy";
import { HauseStudy } from "@/components/HauseStudy";
import { Acts } from "@/components/Acts";
const Kicker = ({ children }: { children: React.ReactNode }) => <p className="kicker record-voice">{children}</p>;
const TextLink = ({ href, children }: { href: string; children: React.ReactNode }) => <Link className="text-link" href={href}>{children}<span aria-hidden="true">↗</span></Link>;
export default function Home() {

 return <main id="main" className="homepage">
  <section className="scene identity" data-scene="00" aria-labelledby="proposition"><Media id="hero-identity" priority className="scene-background"/><div className="hero-overline record-voice"><span>CHRIS HAY</span><span>LONDON · 2026</span></div><div className="identity-copy"><h1 id="proposition">A house for<br/><em>ideas, systems</em><br/>and objects.</h1><p className="hero-philosophy">{HOUSE.proposition}</p></div><div className="scene-bottom record-voice"><span>RESEARCH · ENGINEERING · DESIGN · FILM</span><a href="#person">THE RECORD BEGINS HERE ↓</a></div></section>
  <div className="opening-caption"><span className="record-voice">IDEA → SYSTEM → OBJECT</span><p>{HOUSE.description}</p><span className="record-voice">EST. IN CURIOSITY</span></div>
  <section id="person" className="scene person-scene" data-scene="01"><Media id="portrait-editorial" className="portrait"/><div className="person-copy"><Kicker>01 / THE PERSON</Kicker><h2>Chris<br/><em>Hay.</em></h2><p className="practice">{HOUSE.personLine}</p><div className="inline-links"><TextLink href="/about">ABOUT</TextLink><a className="text-link" href="https://www.linkedin.com/in/chrishayuk/">LINKEDIN ↗</a></div></div></section>
  <section className="scene youtube-home" data-scene="01-youtube" aria-labelledby="latest-youtube-heading"><YouTubeScene/></section>
  <section className="scene moe-scene moe-home dark-scene" data-scene="02"><MoeScene/></section>
  <section className="scene interlude" data-scene="03" aria-label="London photograph"><Media id="london-night" className="scene-background"/><div className="scene-bottom record-voice"><span>LONDON</span><span>03 / BETWEEN THINGS</span></div></section>
  <section className="scene question-scene" data-scene="04"><div className="question-media"><Media id="ffn-notebook"/></div><div className="question-copy"><Kicker>04 / CURRENT QUESTION · FFN</Kicker><span className="status-label">● OPEN</span><h2>What if<br/>the FFN<br/><em>is a graph?</em></h2><TextLink href="/research/ffn-as-graph">FOLLOW THE THREAD</TextLink></div></section>
  <section className="scene vindex-scene dark-scene" data-scene="05"><div className="project-intro"><Kicker>05 / WORK · VINDEX3</Kicker><h2>The model<br/><em>is the database.</em></h2><div className="inline-links"><TextLink href="/work/vindex3">VIEW THE WORK</TextLink><a className="text-link" href="https://vindex3.org/">VINDEX3.ORG ↗</a></div></div><SystemStudy/></section>
  <section className="scene contact-scene" data-scene="06"><div className="section-heading"><Kicker>06 / SELECTED FILMS</Kicker><h2>Watch<span className="amber">.</span></h2><TextLink href="/film">ALL FILMS</TextLink></div><FilmSelection/></section>
  <section className="scene larql-scene" data-scene="07"><div className="larql-photo"><Media id="larql-object"/></div><div className="larql-copy"><Kicker>07 / WORK · LARQL</Kicker><h2>Models are<br/>places<br/><em>you can go.</em></h2><p>Querying learned systems.</p><TextLink href="/work/larql">VIEW THE WORK</TextLink></div><div className="larql-system"><SystemStudy variant="query"/></div></section>
  <section className="scene personal-scene" data-scene="08" aria-label="Personal photographs"><div className="personal-caption record-voice">08 / THE WORLD AROUND THE WORK</div><Media id="personal-architecture" caption/><Media id="personal-books" caption/><Media id="personal-journey" caption/></section>
  <section className="scene notebook-scene" data-scene="09"><Media id="operator-notebook"/><div className="notebook-copy"><Kicker>09 / NOTEBOOK</Kicker><div className="note-meta record-voice"><span>N-OPERATOR</span><span>THOUGHT · OPEN</span></div><h2>The operator knows<br/><em>where the model goes.</em><br/><br/>It doesn’t know<br/><em>what the model does.</em></h2><div className="inline-links"><TextLink href="/notebook/the-operator-and-the-model">READ THE NOTE</TextLink><Link className="text-link" href="/notebook/the-operator-and-the-model#cite">REFERENCE</Link></div><p className="record-voice notebook-footnote">A THOUGHT, BEFORE AN EXPERIMENT.</p></div></section>
  <section className="scene hause-scene" data-scene="10"><Kicker>10 / THE LANGUAGE OF THE RECORD</Kicker><HauseStudy/><div className="hause-bottom"><p>THIS SITE IS COMPOSED WITH HAUSE.</p><a className="text-link" href="https://hause.design/">EXPLORE HAUSE.DESIGN ↗</a></div></section>
  <section className="scene mcp-scene dark-scene" data-scene="11"><Media id="mcp-interaction" className="scene-background"/><div className="scene-copy"><Kicker>11 / SYSTEM · MCP</Kicker><h2>Machines<br/><em>using machines.</em></h2><div className="inline-links"><TextLink href="/work/mcp-cli">MCP-CLI</TextLink><TextLink href="/work/mcp-cli#chuk">CHUK</TextLink></div></div></section>
  <section className="scene finding-scene" data-scene="12"><Kicker>12 / THE BOUNDARY OF WHAT WE KNOW</Kicker><div className="finding-heading"><span className="record-voice">OPEN QUESTION / RESIDUAL GEOMETRY</span><h2>Present.<br/><em>But predictive?</em></h2></div><Acts acts={[{ kind: "refusal", title: "PREDICTIVE LOCALITY IS NOT ESTABLISHED", lines: ["Working note: expert co-activation observed", "Untested: useful working-set prediction"], principle: "An observation is the beginning of an experiment." }]}/><TextLink href="/research/residual-geometry">READ THE QUESTION</TextLink></section>
  <section className="scene closing-scene dark-scene" data-scene="13"><Media id="closing-portrait" className="scene-background"/><div className="closing-copy"><Kicker>13 / STILL CURIOUS</Kicker><h2>Chris Hay.</h2><p className="record-voice">IDEAS · SYSTEMS · OBJECTS · LONDON</p></div></section>
 </main>;
}
