import Link from "next/link";
import { FieldNotes } from "@chrishayuk/hause/components/FieldNotes";
import { EvidenceTable } from "@chrishayuk/hause/components/EvidenceTable";
import { AddressTransplant, AddressCoordinates } from "./AddressBuildStudies";
import { arms, armNames, causal, components, layers, reader, readability, sourceCommit, sourceRoot, transplant } from "@/lib/address-build";
import registry from "@/lib/data/address-build-registry.json";

function ReadabilityTable() {
  return <EvidenceTable className="address-evidence" caption="Held-out accuracy · Part 2b · mean across 3 folds" rowLabel="Depth"
    columns={components.map(id => ({ id, label: id, precision: 2 }))}
    rows={layers.map(layer => ({ id: String(layer), label: `L${layer}`, note: layer >= 28 ? "Answer-token endpoint" : undefined,
      values: Object.fromEntries(components.map(c => [c, readability(layer, c)])) }))}
    source={{ label: "Full-precision reader results", href: "/data/address-build-1/reader.json" }} />;
}
function CausalTable() {
  return <EvidenceTable className="address-evidence" caption="All transplant arms · KL over the full vocabulary" rowLabel="Depth / donor"
    columns={[{ id: "n", label: "n", unit: "transplants" }, { id: "retention", label: "Recipient retained", format: "percent" },
      { id: "donor", label: "Donor answer", format: "percent" }, { id: "kl", label: "Median KL", precision: 3 }]}
    rows={layers.flatMap(layer => arms.map((arm, i) => { const value = transplant(layer, arm); return {
      id: `${layer}-${arm}`, label: `L${layer} · ${armNames[i]}`, values: { n: value.n, retention: value.retention,
        donor: value.donor_answer_rate === null ? { missing: "not-applicable" as const, reason: "Same-binding donor" } : value.donor_answer_rate,
        kl: value.median_kl } }; }))}
    source={{ label: "Full-precision causal results", href: "/data/address-build-1/causal.json" }} />;
}
function TransferTables() {
  return <>{components.map(component => <EvidenceTable className="address-evidence" key={component} caption={`${component} · cross-layer reader transfer`} rowLabel="Transition"
    columns={[{ id: "identity", label: "Raw", precision: 2 }, { id: "norm_only", label: "Norm only", precision: 2 },
      { id: "procrustes", label: "Procrustes", precision: 2 }, { id: "same_layer_reference", label: "Same layer", precision: 2 }]}
    rows={Object.entries(reader.cross_layer_transfer[component]).map(([transition, values]) => ({ id: transition, label: transition.replace("->", " → "), values }))}
    source={{ label: "Full-precision reader results", href: "/data/address-build-1/reader.json" }} />)}</>;
}

export function AddressBuildNotebook() {
  return <div className="address-notebook">
    <nav className="address-chapter-nav record-voice" aria-label="Evidence and research record"><a href="#address-causal">02 / TRANSPLANT ↓</a><a href="#address-coordinates">03 / COORDINATES ↓</a><a href="#address-record">04 / OPEN THE RECORD ↓</a></nav>
    <section className="map-visual-section" id="address-causal"><span className="record-voice map-section-label">THE CAUSAL QUESTION</span><h2>What does the state<br /><em>actually control?</em></h2><AddressTransplant/><p className="notebook-boundary">At L20, the final-position state carries a usable relation frame but does not override the recipient’s entity. By L28, the wrong-entity donor controls the answer.</p></section>
    <section className="map-visual-section" id="address-coordinates"><span className="record-voice map-section-label">THE CHART QUESTION</span><h2>The relation survives.<br /><em>The coordinates change.</em></h2><AddressCoordinates/></section>
    <section id="act-5" className="address-interpretation" aria-label="Interpretation and scope"><div><span className="record-voice">WHAT THIS MEANS</span><h2>Relation first.<br />Entity binding later.</h2><p>The evidence supports staged construction in the final-position residual, through changing intermediate representations.</p></div><aside><span className="record-voice">AT THE WIDTH IT WAS EARNED</span><p><strong>One model. Two relations.</strong><br />Gemma 3 4B IT; capital versus language.</p><p><strong>One position.</strong><br />Earlier tokens still carry the entity. This does not show it is absent elsewhere.</p><p><strong>L28–30 is an endpoint.</strong><br />Answer-token availability confounds late readability. The mechanistic window is L8–24.</p><p><strong>A coincidence is not a cause.</strong><br />Whether the relation basis change enables entity binding remains open.</p></aside></section>
    <section className="address-record" id="address-record"><div id="act-6" className="address-record-heading"><div><span className="record-voice">04 / INSTRUMENT & RECORD</span><h2>ADDRESS-BUILD-1</h2><p>Gemma 3 4B IT · bf16 · 2026-09-06<br />Causal transplant + cross-layer reader</p></div><div className="address-splice-floor"><span className="record-voice">SELF-SPLICE / MAX LOGIT Δ</span><strong>0.000e+00</strong><small>Bit-identical before any arm was scored.</small></div></div>
      <div className="address-record-facts record-voice"><span>48 CAUSAL PROMPTS</span><span>194 READER PROMPTS</span><span>7 DEPTHS</span><span>3 READER FOLDS</span></div>
      <FieldNotes className="address-notes" label="Methodology & frozen gates" detail="READ +"><div><p><strong>Causal half.</strong> Replace only the residual entering layer L at the final prompt position. Continue the remaining layers normally and read next-token logits; no generation and no weight editing. Four wordings, 48 retained prompts, {causal.n_transplants.toLocaleString("en-GB")} transplants. The different-relation arm has 23 eligible pairs per depth; the other arms have 48.</p><p>The primary gap compares full-vocabulary KL under wrong-binding and same-binding transplants. Recipient retention alone is insufficient: donor-answer rate distinguishes incompatibility from transporting a value. Self-splicing must reproduce the baseline bit-identically.</p><p><strong>Reader Part 2b.</strong> 194 retained prompts, 20 bindings, 14 entities, capital and language, 12 wordings. Three folds hold out 4 wordings and train on 8. PCA dimension 128; ridge 1.0. Component-specific same-layer gates were frozen before measurement: relation ≥ .85, entity ≥ .40, binding ≥ .30. All pass, but entity and binding pass only in the confounded endpoint band.</p><p><strong>The original hypothesis needed reframing.</strong> Wrong-entity swaps were as harmless as same-binding swaps through L20, so the early convergence is not binding-specific. The original causal gate condition 2 failed. Coordinate-change support is for relation only.</p><p><strong>Bank boundary.</strong> Currency and continent could not be made reachable with the same wording bank. Relation-specific wordings would entangle relation with phrasing. This note makes no claim beyond capital versus language.</p></div></FieldNotes>
      <FieldNotes className="address-notes" label="Complete measurements" detail="READ +"><div><ReadabilityTable/><p>* L28–30 may be answer decoding. Chance floors: relation .50; entity .071; binding .05. Weak early entity/binding readability is not evidence of complete absence.</p><CausalTable/><TransferTables/><p>All displayed tables round values for reading. The JSON files retain full recorded precision, gate values and the causal KL gap at each depth.</p></div></FieldNotes>
      <FieldNotes className="address-notes" label="The failed reader stays in the record" detail="READ +"><div><p>The first Part 2 had about 1.5 training examples per binding class. Entity accuracy stayed around .14 in all 21 cells. It is an instrument failure, not evidence about the model. Part 2b repairs coverage and uses component-specific gates; the relation threshold was raised to .85 before readability was inspected.</p><a href="/data/address-build-1/reader-failed.json" download>Download preserved Part 2 result ↓</a></div></FieldNotes>
      <FieldNotes className="address-notes" label="Registry, hashes & source provenance" detail="READ +"><div><p className="record-voice">{registry.id}<br />CONSOLIDATED WRITE-UP / V{registry.latest_writeup.version}<br />SOURCE / {sourceCommit}</p><p>The registry snapshot comes from chuk-experiments. Result JSON was extracted from the registered commit in the local LARQL repository. The public GitHub API did not resolve that commit at verification time; the frozen downloads below remain available with this note.</p><dl className="address-hashes"><dt>Causal rows SHA-256 (reported by harness)</dt><dd>{causal.rows_sha256}</dd><dt>Reader Part 2b result SHA-256 (reported by harness)</dt><dd>{reader.result_sha256}</dd></dl><p>These are the harness’s payload hashes, not hashes of the formatted download files. The NPZ state captures were excluded by the source repository’s *.npz rule. Recorded aggregates support this recreation; they are not a complete state-capture archive.</p><p><a href={sourceRoot}>Registered source location ↗</a></p><div className="address-downloads">{[{ file: "registry", label: "Registry + design + write-up" }, { file: "causal", label: "Causal results" }, { file: "reader", label: "Reader Part 2b" }, { file: "reader-failed", label: "Failed reader Part 2" }].map(item => <a key={item.file} download href={`/data/address-build-1/${item.file}.json`}>{item.label} ↓</a>)}</div></div></FieldNotes>
    </section>
    <Link href="/notebook/what-is-the-map" className="map-authority-branch"><span className="record-voice">RETURN TO THE QUESTION / N-MAP</span><p>What is the map<br />actually a map of? <span>↗</span></p></Link>
  </div>;
}
