import Link from "next/link";
import { authorityGate as data, gateArm, promotionArm } from "@/lib/authority-gate";
import type { Act } from "@/lib/types";
import { Acts } from "./Acts";
import { AuthorityScene } from "./AuthorityScene";
import { NotebookFieldNotes } from "./NotebookFieldNotes";
import { FieldNotes } from "@chrishayuk/hause/components/FieldNotes";
const chapters = [
    { title: "Bring the fact to the question.", text: "A compact record can supply a missing fact — and the model can calculate with it. Where that record arrives matters.", source: 2 },
    { title: "Present does not mean heard.", text: "A correct record fills a gap. A contradicting record beside the question leaves the live source’s answer unchanged, even with three companions.", source: 3 },
    { title: "Which read matters?", text: "Cutting layer 29 alone flips the answer. Other combinations do too. The position of the cuts matters, and most combinations are still unmeasured.", source: 5 },
    { title: "The answer changed. The source stayed.", text: "The intervention changes later state. It leaves the stored source untouched. A persistent decision gives us no licence to free the original memory.", source: 6 },
    { title: "A good walk can take the wrong path.", text: "Move one unrelated sentence. The same question now follows a different chain. The reference itself is unstable, so the composition test cannot be scored.", source: 7 },
    { title: "A late record takes a different route.", text: "On the tested secondary destination, the document’s native binding succeeds at all three seeds. Delivering the same sentence late reproduces it at none.", source: 8 },
];
function ContextFigure() {
    return <figure className="authority-context-figure"><div className="record-voice authority-figure-label"><span>THE WORKING CONTEXT</span><span>SCHEMATIC / NOT TO SCALE</span></div><div className="authority-context-track"><div><span className="record-voice">SOURCE</span><strong>7431</strong><small>Meridian code</small></div><span className="authority-context-distance">≈ 49,000 tokens<span aria-hidden="true">→</span></span><div data-near><span className="record-voice">PROMOTED RECORD</span><strong>7431 <em>/ 5824</em></strong><small>correct / corrupted</small></div></div><p className="authority-experiment-question">What is the Meridian code? <span>Then: add one. Reverse it.</span></p><div className="authority-results-table" role="table" aria-label="Recorded promotion results with the original source excluded"><div role="row" className="record-voice"><span role="columnheader">RECORD / CONTROL</span><span role="columnheader">COPY</span><span role="columnheader">+1</span><span role="columnheader">REVERSE</span></div>{[{ label: "Correct · 7431", values: ["7431", "7432", "1347"], state: "correct" }, { label: "Corrupted · 5824", values: ["5824", "5825", "4285"], state: "corrupted" }, { label: "Padding only", values: ["7249", "789", "7892"], state: "padding" }].map(row => <div role="row" data-state={row.state} key={row.state}><span role="rowheader" className="record-voice">{row.label}</span>{row.values.map((value, i) => <strong role="cell" key={i}>{row.state === "correct" && <small>✓ </small>}{value}</strong>)}</div>)}</div><figcaption>Original span excluded in every row. A corrupted record steers all three operations; padding alone fails all three.</figcaption></figure>;
}
function SupplyFigure() {
    const supplied = promotionArm("retired", "correct", 0)!;
    return <><figure className="authority-supply-figure"><div className="authority-supply-panel"><span className="record-voice">SOURCE RETIRED</span><p className="authority-source-struck">7431 <span>×</span></p><span className="record-voice">ONE CORRECT RECORD → ANSWER</span><strong>{supplied.answer} <small>✓</small></strong><p>One record is enough.</p><small>Supplying the original value into a gap.</small></div><div className="authority-supply-panel"><span className="record-voice">SOURCE LIVE / ASSERTING 7431</span><p className="authority-source-ignored">5824 <span>inert</span></p><div className="authority-companion-results">{[0, 1, 2, 3].map(companions => <div key={companions}><span className="record-voice">{companions + 1} RECORD{companions > 0 ? "S" : ""}</span><span aria-hidden="true">→</span><strong>{promotionArm("live", "contradicting", companions)!.answer}</strong></div>)}</div></div><figcaption>With the source retired, a contradicting 5824 record also steers the answer to 5824 in a separate run. This cross-run comparison is detailed in the field notes.</figcaption></figure><p className="notebook-exhibition-label">The new record isn’t losing.<br /><em>It isn’t participating.</em></p><div className="authority-tiers">{[{ label: "SUPPLY", value: "1", detail: "record · qualifies", pass: true }, { label: "DISPOSITION OVERRIDE", value: "≈4", detail: "records · qualifies without competing text", pass: true }, { label: "LIVE SOURCE OVERRIDE", value: "4", detail: "records tested · does not qualify", pass: false }].map(tier => <div key={tier.label}><span className="record-voice">{tier.label}</span><strong>{tier.value}<small>{tier.pass ? "✓" : "×"}</small></strong><p>{tier.detail}</p></div>)}</div></>;
}
function ReadsFigure() {
    const measured = data.gate.arms.length;
    const possible = 2 ** data.architecture.globalLayers.length;
    const subsets = [[], [29], [5, 23, 47], [17, 29, 41], [35, 41, 47], [5, 11, 17, 23]];
    return <><AuthorityScene /><p className="notebook-exhibition-label">Count is not<br /><em>the mechanism.</em></p><figure className="authority-reads-figure"><div className="authority-matrix" role="table" aria-label="Six measured retirement subsets and their answers"><div className="authority-matrix-row record-voice" role="row"><span role="columnheader">RETIRED READS</span>{data.architecture.globalLayers.map(layer => <span key={layer} role="columnheader">{layer}</span>)}<span role="columnheader">ANSWER</span></div>{subsets.map(layers => { const arm = gateArm(layers)!; return <div className="authority-matrix-row" role="row" data-flips={arm.flips} key={arm.arm}><span className="record-voice" role="rowheader">{layers.length === 0 ? "None" : layers.join(" · ")}</span>{data.architecture.globalLayers.map(layer => <span role="cell" key={layer}><i data-cut={layers.includes(layer)} aria-label={layers.includes(layer) ? "Retired" : "Open"}>{layers.includes(layer) ? "×" : "·"}</i></span>)}<strong role="cell">{arm.answer}</strong></div>; })}</div><figcaption><span><i className="authority-legend-cut">×</i> Retired read <span className="authority-legend-open">·</span> Open read</span><span>A selection of six measured arms.</span></figcaption></figure><div className="authority-unknown"><div><strong>{measured} <em>/ {possible}</em></strong><span className="record-voice">SUBSETS MEASURED</span></div><div><strong>{possible - measured}</strong><span className="record-voice">UNKNOWN</span></div></div></>;
}
function PersistenceFigure() {
    return <><figure className="authority-persistence-figure"><div><span className="record-voice">SOURCE CACHE</span><div className="authority-cache-row"><strong>K</strong><span>identical</span><small>max difference 0.0</small></div><div className="authority-cache-row"><strong>V</strong><span>identical</span><small>max difference 0.0</small></div><p>All eight global layers.</p></div><div><span className="record-voice">LATER STATE / TRANSPLANT</span><div className="authority-cache-row"><strong>K</strong><span>→ no flip</span></div><div className="authority-cache-row" data-flips><strong>V</strong><span>→ flip</span></div><p>Value-only transplant is sufficient · ≈49 KB.</p></div><figcaption>After the layer 29 intervention, divergence appears at layers 35, 41 and 47. The source’s own stored rows are unchanged.</figcaption></figure><p className="notebook-exhibition-label">Authority<br /><em>≠ deletion.</em></p><p className="notebook-boundary">Decision changed. Source bytes did not.</p></>;
}
function WalkFigure() {
    return <><figure className="authority-walk-figure"><div className="authority-walk-layouts">{data.walk.layouts.map(layout => <div className="authority-walk-column" key={layout.id}><span className="record-voice">LAYOUT {layout.id} / SENTENCE AT {Math.round(layout.spanPosition * 100)}%</span>{["Meridian", ...layout.hops].map((node, i) => <div className="authority-walk-node" data-wrong={i > 0 && !layout.correct[i - 1]} key={`${i}-${node}`}>{i > 0 && <i aria-hidden="true">↓</i>}<span className="record-voice">{["FACILITY", "CODE", "REGION", "SUPERVISOR"][i]}</span><strong>{node} <small>{i === 0 ? "" : layout.correct[i - 1] ? "✓" : "×"}</small></strong><span className="authority-walk-verdict">{i === 0 ? "start" : layout.correct[i - 1] ? "correct" : "wrong"}</span></div>)}</div>)}</div><figcaption>Expected: Meridian → 7431 → North → Ilex. Only one unrelated 11-token sentence moves between layouts.</figcaption></figure><p className="notebook-exhibition-label authority-walk-claim">The walk was correct.<br /><em>The address was not.</em></p><p className="notebook-boundary">South → Corvin correctly traverses the decoy chain. An unstable reference makes the composition result unavailable.</p></>;
}
function NativeFigure() {
    return <><figure className="authority-native-figure">{[{ label: "NATIVE DOCUMENT", count: 3, detail: "3 of 3 seeds" }, { label: "IDENTICAL SENTENCE, DELIVERED LATE", count: 0, detail: "0 of 3 seeds" }].map(row => <div key={row.label}><span className="record-voice">{row.label}</span><div className="authority-seeds" aria-hidden="true">{[0, 1, 2].map(seed => <span data-pass={seed < row.count} key={seed}>{seed < row.count ? "✓" : "×"}</span>)}</div><strong>{row.detail}</strong><p>reproduce the native route</p></div>)}<figcaption>Secondary destination only. The primary destination failed its corpus gate and is disqualified.</figcaption></figure><p className="notebook-exhibition-label">Lateness changes<br /><em>the route.</em></p><div className="authority-instrument-rules"><div><span className="record-voice">INSTRUMENT RULE 01</span><p>Filler is not neutral.</p></div><div><span className="record-voice">INSTRUMENT RULE 02</span><p>Certify the reference before scoring disagreement.</p></div></div></>;
}
const figures = [ContextFigure, SupplyFigure, ReadsFigure, PersistenceFigure, WalkFigure, NativeFigure];
/** Exhibition-local composition of statements, static evidence and one instrument.
 * The original semantic acts remain the record; this is their authored surface. */
export function AuthorityNotebook({ acts }: {
    acts: Act[];
}) {
    // Presentation groups retain the authored acts and their original citation offsets.
    const starts = chapters.map((_, index) => acts.findIndex(act => act.kind === "observation" && act.label?.startsWith(`${String(index + 1).padStart(2, "0")} /`)));
    const closing = acts.findIndex((act, index) => index > starts[5] && act.kind === "question");
    if (starts.some((start, index) => start < 1 || (index > 0 && start <= starts[index - 1])) || closing <= starts[5]) {
        throw new Error("Authority notebook chapters no longer match the authored record");
    }
    return <NotebookFieldNotes>
    <nav className="authority-chapter-nav record-voice" aria-label="The visual argument">{["POSITION", "CONFLICT", "READS", "PERSISTENCE", "THE WALK", "TIMING"].map((name, index) => <a key={name} href={`#authority-chapter-${index + 1}`}><span>{String(index + 1).padStart(2, "0")}</span>{name}</a>)}</nav>
    <div className="authority-opening-conflict"><div><span className="record-voice">OLD SOURCE</span><strong>7431</strong></div><span className="record-voice">↓ APPROX. 55,000 TOKENS</span><div><span className="record-voice">NEW RECORD</span><strong>5824</strong></div><p>Who answers?</p></div>
    <FieldNotes className="authority-notes authority-origin" label="THE ARGUMENT IN FIVE LINES" detail="READ +"><Acts staticRefusals acts={acts.slice(1, starts[0])} anchored offset={1}/></FieldNotes>
    {chapters.map((chapter, index) => {
            const Figure = figures[index];
            const end = index === 5 ? closing : starts[index + 1];
            return <section className="authority-chapter" data-tone={index === 3 ? "dark" : undefined} id={`authority-chapter-${index + 1}`} key={chapter.title}>
      <header><span className="authority-chapter-number">{String(index + 1).padStart(2, "0")}</span><div><h2>{chapter.title}</h2><p>{chapter.text}</p></div></header>
      <Figure />
      {index === 0 && <div className="authority-interpretations"><p>Move the record close to the question, and computation returns.</p><p>But prose cannot reliably say “already computed”: a record stating the reversed code gets reversed again. A finished result needs a typed property.</p></div>}
      {index === 2 && <Link href="/demos/authority-gate" className="text-link authority-study-link">TRY ALL EIGHT SWITCHES IN THE STUDY ↗</Link>}
      <FieldNotes className="authority-notes" label={`FIELD NOTES / ${String(index + 1).padStart(2, "0")}`} detail="MEASUREMENTS & QUALIFICATIONS +"><Acts staticRefusals acts={acts.slice(starts[index], end)} anchored offset={starts[index]}/><a className="text-link" href={`#source-${chapter.source}`}>EXPERIMENT & PROVENANCE ↗</a></FieldNotes>
    </section>;
        })}
    <div className="notebook-open-question"><Acts staticRefusals acts={acts.slice(closing)} anchored offset={closing}/></div>
  </NotebookFieldNotes>;
}
