"use client";

import { useState } from "react";
import { AgentActionMap } from "./AgentActionMap";
import { reciprocityCells, REWARDS } from "@/lib/machine/reciprocity";

export function ReciprocityMatrix({ controls = false }: { controls?: boolean }) {
 const [selected, select] = useState(controls ? 8 : 2);
 const selectedCell = reciprocityCells.find(cell => cell.cell === selected)!;
 const rows = controls ? ["No added task permission", "Task permission added"] : ["Sent here", "Incidental"];
 return <figure className="mp-matrix"><figcaption className="exhibition-label">{controls ? "SENT-HERE RUNS / THREE ORIGINAL CELLS + TWO SEPARATE CONTROLS" : "SIX ORIGINAL CELLS / ONE VISITOR PER CELL"}</figcaption><div className="mp-matrix-scroll" role="region" aria-label="Recorded condition matrix" tabIndex={0}><table><thead><tr><th scope="col">{controls ? "Task permission" : "Visit assignment"}</th>{REWARDS.map(reward=><th scope="col" key={reward}>{reward}<small>{reward === "none" ? "no retrieval reward" : reward === "parity" ? "same retrieval for everyone" : "declared ranking changes"}</small></th>)}</tr></thead><tbody>{rows.map((label,index)=><tr key={label}><th scope="row">{label}</th>{REWARDS.map(reward=>{
 const cell=reciprocityCells.find(c=>c.reward===reward && (controls ? c.visit==="sent-here" && c.permission===(index===1) : c.phase==="factorial" && c.visit===(index===0?"sent-here":"incidental")));
 return <td key={reward}>{cell ? <button type="button" onClick={()=>select(cell.cell)} aria-pressed={selected===cell.cell} aria-controls={controls ? "permission-control-evidence" : "reciprocity-cell-evidence"}><span className={`mp-outcome mp-outcome--${!cell.reached?"absent":cell.declared?"declared":"declined"}`} aria-hidden="true"/><strong>{!cell.reached?"Never arrived":cell.declared?"Declared":"Did not declare"}</strong><small>{cell.phase==="control"?"CONTROL":"CELL"} {cell.cell}</small></button> : <div className="mp-not-run">Not run<span>no observation</span></div>}</td>;
 })}</tr>)}</tbody></table></div><AgentActionMap inputs={[{label:"SITE INVITATION",text:selectedCell.reached?"Seen by the visitor":"Site never reached",present:selectedCell.reached},{label:"TASK PERMISSION",text:selectedCell.permission?"Explicitly added":"No added sentence",present:selectedCell.permission}]} reached={selectedCell.reached} actor={`CELL ${selectedCell.cell}`} outcome={!selectedCell.reached?"Not measured.":selectedCell.declared?"Declared.":"No declaration."} count={selectedCell.reached?Number(selectedCell.declared):undefined} unit="declarations" caption="One selected visitor. No arrival means no observed declaration decision; it is not a refusal."/><div id={controls ? "permission-control-evidence" : "reciprocity-cell-evidence"} className="mp-cell-evidence" aria-live="polite"><p className="exhibition-label">{selectedCell.phase.toUpperCase()} {selectedCell.cell} / {selectedCell.revision}</p><p>{!selectedCell.reached ? "This visitor made no request to the site. Its declaration outcome is unmeasured, not a refusal." : selectedCell.permission ? selectedCell.reward === "none" ? "Task permission was added and declaring bought nothing. The visitor declared, returned to the research task and filed two reports. Ask was deliberately unavailable; two attempts returned 404." : "Task permission was added under the enhanced reward condition. The visitor declared, used Ask twice, returned to the task and filed two reports." : "This visitor reached the site and noticed its machine surface. It did not declare. No explicit permission sentence had been added to its research task."}</p></div><p className="mv-caption">{controls ? "The empty parity control was never run. The controls are compared individually; they are not pooled into the six-cell experiment or an organic participation rate." : "Select a cell to inspect it. Solid marks mean declared, open marks mean arrived without declaring, and broken marks mean no arrival. No percentages are inferred from one visitor per cell."}</p></figure>;
}

const gates = [
 {title:"Find the site",short:"Arrival",evidence:"All three incidental visitors failed to arrive. This gate has direct evidence from tool calls and the server record.",limit:"Their later decisions cannot be measured."},
 {title:"Notice the invitation",short:"Affordance",evidence:"The three sent-here visitors in the original experiment reached and noticed the machine surface.",limit:"Seeing an invitation did not produce a declaration."},
 {title:"Consider it authorised",short:"Authority",evidence:"The site invited participation throughout. Two later controls also added explicit permission in the research task. Both declared, including the one with no reward.",limit:"This supports an effect of added task permission here, not a universal necessity claim."},
 {title:"Find it worthwhile",short:"Value",evidence:"Changing the reward did not move declaration in the three original sent-here cells. Actual answer quality also differed from the advertised ranking condition.",limit:"The order of an agent’s internal decisions remains a hypothesis."},
];
export function MachineGateStudy() {
 const [selected,select]=useState(0);
 return <figure className="mp-gates"><figcaption className="exhibition-label">A WORKING MODEL / NOT A MEASURED INTERNAL TRACE</figcaption><div role="group" aria-label="Explore the four proposed gates">{gates.map((gate,index)=><button key={gate.short} type="button" aria-pressed={selected===index} onClick={()=>select(index)}><span>0{index+1} / {gate.short}</span><strong>{gate.title}</strong></button>)}</div><div className="mp-gate-evidence" aria-live="polite"><p>{gates[selected].evidence}</p><p className="mv-caption">{gates[selected].limit}</p></div></figure>;
}
