import {ibmAppearances,panelistIntroduction,firstEpisodeSource} from "@/lib/ibm-appearances";
import Link from "next/link";
import {FilmPlayer} from "./FilmPlayer";
import {ibm,ibmVideos,latestMoe,popularMoe,videoPath,durationLabel,viewLabel} from "@/lib/youtube";
export function MoeSelection(){return <section className="moe-selection"><div className="section-heading"><p className="kicker record-voice">FILM / IBM · WITH CHRIS HAY</p><h2>Mixture<br/><em>of Experts.</em></h2><Link href="/film/mixture-of-experts" className="text-link">THE COLLECTION ↗</Link></div><div className="moe-pair">{[{video:latestMoe,label:"LATEST APPEARANCE"},{video:popularMoe,label:"MOST VIEWED"}].map(({video:v,label})=><article key={label}><p className="kicker record-voice">{label} / EPISODE {v.episode}</p><FilmPlayer video={v}/><Link className="film-caption" href={videoPath(v)}><h3>{v.title}</h3><span className="record-voice">{durationLabel(v.duration)} ↗</span></Link><p className="moe-meta record-voice">{v.published} · {viewLabel(v)}</p></article>)}</div></section>;}
export function MoeScene(){const v=latestMoe;return <><div className="moe-home-heading"><p className="kicker record-voice">02 / FILM · IBM</p><h2>Mixture<br/><em>of Experts.</em></h2><Link className="text-link" href="/film/mixture-of-experts">ENTER THE COLLECTION ↗</Link></div><div className="moe-home-screen"><p className="kicker record-voice">LATEST APPEARANCE / EPISODE {v.episode} · {v.published}</p><FilmPlayer video={v}/><Link className="film-caption" href={videoPath(v)}><h3>{v.title}</h3><span className="record-voice">{durationLabel(v.duration)} ↗</span></Link></div><div className="moe-home-credit record-voice"><span>PRODUCED BY IBM · WITH CHRIS HAY</span><Link href="/film/mixture-of-experts?sort=popular">MOST VIEWED EPISODES ↗</Link></div></>;}
export function MoeCollection({sort="latest"}:{sort?:string}){
 const popular=sort==="popular";const films=[...ibmVideos].sort(popular?(a,b)=>(b.views??-1)-(a.views??-1):(a,b)=>(b.published||"").localeCompare(a.published||""));
 const first=films[0];const mostViewedOverall=popularMoe.youtubeId===ibm.playlistMostViewedId;
 return <main id="main" className="moe-world"><header className="index-intro"><p className="kicker record-voice">FILM / IBM · WITH CHRIS HAY</p><h1>Mixture<br/><em>of Experts.</em></h1><p className="dek">A regular panelist.<br/>Since episode one.</p><div className="moe-panelist-intro" id="panelist"><p>{panelistIntroduction}</p><div className="inline-links"><a className="text-link" href={firstEpisodeSource}>THE FIRST EPISODE ↗</a><a className="text-link" href="#appearance-record">{ibmAppearances.verifiedCount} VERIFIED APPEARANCES ↓</a></div></div><div className="moe-order record-voice" aria-label="Episode order"><Link href="/film/mixture-of-experts" aria-current={!popular?"page":undefined}>LATEST APPEARANCE</Link><Link href="/film/mixture-of-experts?sort=popular" aria-current={popular?"page":undefined}>MOST VIEWED</Link><a href={ibm.playlistUrl}>FULL IBM PLAYLIST ↗</a></div></header>
 <section className="moe-leading"><p className="kicker record-voice">{popular?"MOST VIEWED":"LATEST APPEARANCE"} / EPISODE {first.episode} · {first.published}</p><FilmPlayer video={first} priority/><div className="moe-leading-caption"><Link href={videoPath(first)}><h2>{first.title} ↗</h2></Link><div className="record-voice"><span>{durationLabel(first.duration)}</span><span>{viewLabel(first)}</span></div></div></section>
 <section className="moe-more">{[popular?latestMoe:popularMoe].filter(v=>v.id!==first.id).map(v=><article key={v.id}><p className="kicker record-voice">{v.youtubeId===popularMoe.youtubeId?"MOST VIEWED":"LATEST APPEARANCE"} / EPISODE {v.episode}</p><FilmPlayer video={v}/><Link className="film-caption" href={videoPath(v)}><h3>{v.title}</h3><span className="record-voice">{durationLabel(v.duration)} ↗</span></Link><p className="moe-meta record-voice">{v.published} · {viewLabel(v)}</p></article>)}</section>
 <section className="moe-source-note"><div className="moe-appearance-record" id="appearance-record"><h2>The appearance record.</h2><p>At least {ibmAppearances.verifiedCount} appearances confirmed from {ibmAppearances.metadataChecked} publicly readable video descriptions in IBM’s official playlist. Numbered episodes are counted once; the register also includes bonus editions. Some descriptions omit panelist names, so this is a minimum confirmed count.</p><p className="record-voice">CHECKED {ibmAppearances.asOf.slice(0,10)} · FIRST APPEARANCE {ibmAppearances.firstEpisode.published}</p><details><summary>EXPLORE THE {ibmAppearances.verifiedCount} CONFIRMED APPEARANCES</summary><ol>{ibmAppearances.appearances.map(r=><li key={r.youtubeId}><Link href={`/film/youtube/${r.youtubeId}`}><span className="record-voice">{r.published}{r.episode?` / EP. ${r.episode}`:""}</span><span>{r.title} ↗</span></Link></li>)}</ol></details></div><p className="record-voice">SOURCE / IBM TECHNOLOGY · {ibm.retrievedAt.slice(0,10)}</p><p>Selected appearances with Chris Hay, verified against IBM’s video credits. {mostViewedOverall?`Episode ${popularMoe.episode} has the highest view count in the ${ibm.playlistCount}-entry official playlist snapshot.`:"View counts order the selected appearances."} Figures are a dated snapshot and will change.</p><p>Produced and published by IBM. Full films play through YouTube. The original episodes and production credits remain with IBM.</p><div className="inline-links"><a className="text-link" href={ibm.playlistUrl}>ALL IBM EPISODES ↗</a><Link className="text-link" href="/film">ALL FILM COLLECTIONS ↗</Link></div></section></main>;
}
