import { JsonLd } from "@chrishayuk/hause/components/JsonLd";
import Link from "next/link";
import { Citation } from "@chrishayuk/hause/components/forms/Citation";
import { Provenance } from "@chrishayuk/hause/components/forms/Provenance";
import { citationLd } from "@chrishayuk/hause/seo";
import { Acts } from "./Acts";
import { Reference } from "./Reference";
import { citationRecord, referenceFormats } from "@/lib/citations";
import { getRecord, recordPath, sectionFor, SITE, records } from "@/lib/records";
import type { PublicationRecord } from "@/lib/types";
export function RecordPage({ record }: { record: PublicationRecord }) {
 const citation = citationRecord(record); const related = [...record.related.map(getRecord).filter(r => r !== undefined), ...records.filter(r => r.youtubeId && r.related.includes(record.id)).slice(0,4)];
 const opening = record.kind === "notebook" && (record.body[0]?.kind === "film" || record.body[0]?.kind === "photograph");
 const demonstration = record.body.find(act => act.kind === "connection" && act.demonstration);
 const demoLink = demonstration?.kind === "connection" ? demonstration.links[0] : undefined;
 const structured = citation ? citationLd(citation) : { "@context": "https://schema.org", "@type": "CreativeWork", "@id": `${SITE}${recordPath(record)}`, name: record.title, abstract: record.abstract, author: { "@type": "Person", name: "Chris Hay" }, creativeWorkStatus: "Draft", dateCreated: record.created, version: record.version };
 return <main id="main" className={`publication-main${opening ? " notebook-record" : ""}`}><JsonLd data={structured}/><header className="record-header"><nav className="breadcrumbs record-voice" aria-label="Breadcrumb"><Link href="/">CHRIS HAY</Link><span>/</span><Link href={record.kind === "work" ? "/systems" : `/${sectionFor(record)}`}>{record.kind === "work" ? "SYSTEMS" : sectionFor(record).toUpperCase()}</Link><span>/ {record.id}</span></nav><div className={opening ? "notebook-opening" : undefined}><div><h1>{record.title}</h1><p className="dek">{record.dek}</p>{opening && <div className="notebook-entrances"><a className="text-link notebook-read" href="#thread">FOLLOW THE QUESTION ↓</a>{demoLink && <a className="text-link notebook-demo-link" href={demoLink.href}>TRY THE INTERACTIVE STUDY ↗</a>}</div>}</div>{opening && <div className="notebook-opening-media"><Acts acts={[record.body[0]]} anchored priority/></div>}</div>{record.kind === "work" && <p className="work-endorsement record-voice">A SYSTEM BY <Link href="/about#the-house">CHRIS HAY ↗</Link></p>}<p className="record-summary">{record.abstract}</p><div className="record-bar record-voice"><span>{record.id}</span><span>{record.status || record.collection}</span><span>RECORDED {record.created}</span><span>{record.publication.toUpperCase()} · V{record.version}</span><a href="#cite">{citation ? "CITE" : "REFERENCE DRAFT"} ↓</a></div></header>
 {record.kind === "film" && <section className="film-record-entry"><span className="record-voice">IBM / MIXTURE OF EXPERTS / EPISODE {record.episode}</span><h2>Enter the conversation.</h2><p>The complete episode and transcript are available from IBM. Follow the original production below.</p><a className="text-link" href={record.originalUrl}>WATCH THE ORIGINAL AT IBM ↗</a></section>}
 <div className="record-body" id="thread"><Acts acts={opening ? record.body.slice(1) : record.body} anchored offset={opening ? 1 : 0}/>{record.slug === "mcp-cli" && <section className="sources" id="chuk"><h2>CHUK / TOOL INFRASTRUCTURE</h2><p>The related projects remain available through <a href="https://github.com/chrishayuk">Chris’s software archive ↗</a>.</p></section>}</div>
 <div className="record-apparatus"><section className="sources"><h2>SOURCES & PROVENANCE</h2><ul>{record.sources.map((s,i) => <li key={i} id={`source-${i+1}`}>{s.url ? <a href={s.url}>{s.title} ↗</a> : <span>{s.title}</span>}{s.note && <p>{s.note}</p>}</li>)}</ul><p className="record-voice">AUTHOR / CHRIS HAY · VERSION / {record.version}</p></section>{related.length>0 && <section className="related-records"><h2>FOLLOW THE RECORD</h2>{related.map(r => <Link key={r.id} href={recordPath(r)}>{r.title}<span>↗</span></Link>)}</section>}{citation ? <><Provenance record={citation} citeHref="#cite"/><Citation record={citation}/></> : <Reference formats={referenceFormats(record)} draft id={record.id}/>}</div></main>;
}
