import Link from "next/link";
import {FilmPlayer} from "./FilmPlayer";
import {VideoArchive} from "./VideoArchive";
import {youtube,featuredVideo,latestVideo,selectedVideos,filterVideos,videoPath,durationLabel,viewLabel,type ChannelVideo} from "@/lib/youtube";
export const previewFor=(v:ChannelVideo)=>v.youtubeId==="8Ppw8254nLI"?"youtube-larql":v.youtubeId==="UvogrjCgaJQ"?"youtube-studio":v.youtubeId==="5_ZiJpl4hvs"?"youtube-latest":undefined;
export function FilmSelection(){return <div className="contact-sheet">{selectedVideos.map((v,i)=><article className={`film-frame frame-${i}`} key={v.id}><FilmPlayer video={v} preview={previewFor(v)}/><Link href={videoPath(v)} className="film-caption"><h3>{v.title}</h3><span className="record-voice">{durationLabel(v.duration)} ↗</span></Link></article>)}</div>;}
export function YouTubeCollection({archive=false}:{archive?:boolean}){
 if(archive)return <main id="main"><header className="index-intro"><p className="kicker record-voice"><Link href="/film/youtube">FILM / YOUTUBE ↗</Link></p><h1>Every<br/><em>question.</em></h1><p className="dek">The full public channel catalogue. {youtube.videos.length} films, from the first experiments to the latest work.</p><p className="catalogue-note record-voice">CATALOGUED {youtube.retrievedAt.slice(0,10)} · VIEWS ARE A SNAPSHOT; ≈ MARKS ROUNDED COUNTS.</p></header><VideoArchive/></main>;
 return <main id="main" className="youtube-world"><header className="channel-intro"><p className="kicker record-voice">FILM / THE CHRIS HAY CHANNEL</p><h1>Thinking<br/><em>out loud.</em></h1><div><p>Questions become experiments.<br/>Experiments become films.</p><nav className="inline-links"><Link className="text-link" href="/film/youtube/archive">ALL {youtube.videos.length} FILMS ↗</Link><a className="text-link" href={youtube.channelUrl}>YOUTUBE ↗</a></nav></div></header>
 <section className="channel-feature" aria-labelledby="channel-feature-title"><FilmPlayer video={featuredVideo} preview={previewFor(featuredVideo)} priority/><div className="channel-feature-copy"><p className="kicker record-voice">THE FEATURE / {durationLabel(featuredVideo.duration)}</p><h2 id="channel-feature-title">The model<br/><em>is a database.</em></h2><p>{featuredVideo.title}</p><Link className="text-link" href={videoPath(featuredVideo)}>THE FILM & THE RECORD ↗</Link></div></section>
 <section className="channel-latest"><div><p className="kicker record-voice">LATEST ON THE CHANNEL</p><h2>Still<br/><em>finding out.</em></h2><p>{latestVideo.title}</p><Link href={videoPath(latestVideo)} className="text-link">WATCH THE LATEST ↗</Link></div><FilmPlayer video={latestVideo} preview={previewFor(latestVideo)}/></section>
 <section className="channel-selection"><div className="section-heading"><p className="kicker record-voice">THREE WAYS INTO THE WORK</p><h2>Start here.</h2></div><FilmSelection/></section>
 <section className="channel-popular"><p className="kicker record-voice">MOST VIEWED / CATALOGUE SNAPSHOT</p><h2>The conversations<br/><em>that travelled.</em></h2><p className="record-voice">{youtube.retrievedAt.slice(0,10)} · ≈ INDICATES ROUNDED VIEWS</p>{filterVideos("","all","views").slice(0,5).map((v,i)=><Link key={v.id} href={videoPath(v)}><span className="record-voice">0{i+1}</span><h3>{v.title}</h3><span className="record-voice">{viewLabel(v)} ↗</span></Link>)}</section>
 <section className="channel-index-link"><p className="kicker record-voice">{youtube.videos.length} FILMS / ONE CONNECTED RECORD</p><Link href="/film/youtube/archive"><h2>The complete<br/><em>index.</em> ↗</h2></Link><p>Search the films. Follow an idea. Return to its source.</p><Link href="/ask" className="text-link">ASK THE WORK ↗</Link></section>
 </main>;
}
