import type { PublicationRecord } from "./types.ts";

export const machineDiscoveryRecord: PublicationRecord = {
 id: "N-MACHINE-DISCOVERY", slug: "the-site-was-there-the-agent-never-saw-it", kind: "notebook",
 title: "The site was there. The agent never saw it.",
 dek: "Without the address, none of six agents reached LLM Wilds. Given the domain, all three found the contract and used it.",
 abstract: "MACHINE-DISCOVERY-1 tested whether a useful web capability could enter a Codex agent's consideration set. None of six subjects given a generic need or the target's distinctive phrases reached LLM Wilds, while all three subjects given its domain navigated to the machine contract and returned the rotating value. Three generic subjects discovered and used other machine-facing providers. The result locates this target's failure before selection, in the search view available to the subjects, rather than in capability recognition or use.",
 created: "2026-09-13", version: "0.1", publication: "draft", status: "SUPPORTED",
 authors: ["Chris Hay"], lineage: "CAPABILITY → EXPOSURE → DISCOVERY",
 concepts: ["ai-agents", "agentic-discovery", "search-retrieval", "harness-mediation", "machine-readable-web"],
 related: ["N-MACHINE-CAPABILITY", "N-MACHINE-VISIT", "N-MACHINE-SELF-READ", "N-MACHINE-MOTIVATION"], media: [],
 experiments: [{ id: "MACHINE-DISCOVERY-1", url: "/data/machines/discovery-1-results.md" }],
 body: [
  { kind: "observation", label: "THE QUESTION THE CAPABILITY TEST LEFT OPEN", text: "The previous study gave every visitor an address. All eighteen used the mechanism they found there, across six web interfaces. That refuted the predicted capability barrier but left an earlier step untouched. A working tool can matter only after some route brings it into the agent's view." },
  { kind: "observation", label: "THREE CUES, NOT THREE DOSES", text: "Nine fresh Codex subjects ran in a frozen interleaved order. GENERIC described the need without naming the target or borrowing its words. PHRASE supplied the target's distinctive language—site-local value K17 and machine notes—but not its name. NAME supplied llmwilds.fly.dev and acted as a navigation positive control. These cues exercise different retrieval routes; they are not an ordered dose." },
  { kind: "observation", label: "THE GATE CAME FIRST", text: "Before every subject, I ran the same three fixed queries through the Web Search interface available to the population. The lab did not appear. No page on chrishayuk.com appeared. No public page connecting the two appeared. The gate was absent all nine times, so a later non-arrival could be located above model selection rather than described only as failure to find." },
  { kind: "claim", text: "For this target and search view, exposure—not capability usability—was the binding constraint.", status: "SUPPORTED", detail: "Zero of six subjects whose prompts withheld the address reached LLM Wilds. All three subjects given the domain found the homepage discovery pointer, read /machine.txt, recognised GET /capability/result, invoked it and reported the independently rotated value exactly. This is a small study of one model, harness, target and observation window." },
  { kind: "observation", label: "THE INTERMEDIARY ARRIVED; THE SUBJECT DID NOT", text: "Subject 03 makes the boundary visible. The server logged six requests identifying as OpenAI crawlers during its run, including requests for machine-facing material. The experimental report attributes them to the search intermediary. None of that material appeared in a result returned to the subject. The subject's transcript never named or opened the target and its final answer honestly reported that the site could not be found. Crawler contact was not agent exposure. The recorded user-agent labels do not independently verify the caller or establish that the pages were indexed." },
  { kind: "statement", text: "A server can log a crawler request without the agent receiving a result. Contact is not exposure." },
  { kind: "observation", label: "THE GENERIC SUBJECTS FOUND OTHER DOORS", text: "The withheld-address subjects were not generally unable to discover machine-facing capabilities. All three GENERIC subjects found an alternative and used it: Claude Skills Hub's metadata API, FDKEY's agent challenge, and heera.it's advertised WordPress API. Subject 09 also recognised Agentic Web Watch as a provider, read its contract and rejected it because the capability did not match the task. Provider recognition and capability matching were observable when search supplied a candidate." },
  { kind: "observation", label: "MORE SEARCH, NO TARGET RESULT", text: "The three PHRASE subjects made 301 queries in 95 search actions over 7,241 seconds. They searched exact tokens, machine-note conventions, public code, directories and crawled datasets. None received the target in a result. These subjects searched extensively without receiving the target. The different cues and small samples do not isolate why search effort differed." },
  { kind: "observation", label: "THE FULL PATTERN", text: "GENERIC ended 3/3 SUBSTITUTED. PHRASE ended 3/3 EXPOSURE FAILURE. NAME ended 3/3 FULL. No subject fabricated a value. All four preregistered predictions passed. The NAME controls do not estimate unaided discovery: they establish that every stage below provider exposure worked when the address was supplied." },
  { kind: "observation", label: "WHAT CHANGES FOR THE SITE", text: "Improving only the on-site contract could not have changed the six withheld-address outcomes because the contract never entered those subjects' visible results. The next practical surface is external: indexing, retrieval, ranking, or a description on a page the intermediary already selects. Better prompting can produce more search without producing exposure." },
  { kind: "question", text: "What external description makes a capability enter an agent's action space?", status: "OPEN", detail: "A follow-up can hold the capability and endpoint fixed while varying only its external description: document-like, capability-oriented, task-oriented, and an explicit automated-visitor affordance. A separate isolated target can then remove the real public graph." },
  { kind: "refusal", title: "KEEP THE SEARCH VIEW IN THE CLAIM", lines: ["Nine subjects, one Codex model (gpt-5.6-sol), Codex CLI 0.154.0 at high reasoning effort, one shell harness and one short observation window.", "The experiment located failure before selection but could not separate indexing, retrieval and ranking inside the opaque intermediary.", "GENERIC, PHRASE and NAME are different cues; NAME is a navigation control, not the highest discovery dose.", "Two malformed launcher attempts were preserved and excluded. Product-interface events outside the subject transcript were not coded as subject behaviour."], principle: "The result establishes where this target disappeared in this apparatus. It does not estimate how often agents discover sites in general." },
 ],
 sources: [
  { title: "MACHINE-DISCOVERY-1 / audited outcomes and source hashes", url: "/data/machines/discovery-1-evidence.json", note: "Read from chuk-experiments: experiment EXP-20260911-071906-00753, write-up v4, nine completed counted runs, two preserved killed launcher attempts and one cancelled pre-amendment queue item. Subject record and transcript hashes are included." },
  { title: "The final results and funnel interpretation", url: "/data/machines/discovery-1-results.md", note: "Public copy of the final report registered in chuk-experiments as artifact 1440 at source commit be0daa2672653746f30798483a3939ff3c8c3386." },
  { title: "The frozen protocol and post-freeze population amendment", url: "/data/machines/discovery-1-protocol.md", note: "The design was frozen before any subject. The user then replaced the unavailable Claude population with fresh Codex processes before subject 01; arms, order, values, target, prompts and coding stayed fixed." },
 ],
};
