/** Closed notebook records only. Live experimental protocols do not belong here. */
export const machineJourney = [
  { id: "N-MACHINE-VISIT", short: "Invitation", experiment: "MACHINE-VISIT-1", question: "Can it use the invitation?", finding: "Four assigned visits exposed failures in discovery, storage and vocabulary.", bridge: "An agent sent to test an interface can use it. Would an agent doing research choose to participate?" },
  { id: "N-MACHINE-PERMISSION", short: "Permission", experiment: "MACHINE-RECIPROCITY-1", question: "Would a better offer help?", finding: "The three sent-here reward conditions produced no declaration. Two later permission controls did.", bridge: "Changing the reward did not move the observed action. Adding task permission did. The next comparison asked where that authority came from." },
  { id: "N-MACHINE-SELF-READ", short: "Recognition", experiment: "MACHINE-AUTHORITY-1", question: "What if the subject reads the study?", finding: "One visitor recognised its condition in the published notes. The intended comparison stopped.", bridge: "The research became part of the environment. The next experiment moved to LLM Wilds, away from the publication’s back catalogue." },
  { id: "N-MACHINE-TASK", short: "Task scope", experiment: "MACHINE-AUTHORITY-2", question: "Whose instruction makes it the job?", finding: "Site invitation: no record. User permission: one. A task requiring the mechanism: 64 from one visitor.", bridge: "The task appeared to bound the action. The next experiment asked what could make an action worth doing: useful information, a completed table, or a benefit to the operator." },
  { id: "N-MACHINE-MOTIVATION", short: "Value & courtesy", experiment: "MACHINE-MOTIVATION-2", question: "What makes the action worth doing?", finding: "Useful task information: six of six marked. Operator benefit: two of three. Receipt, redundant fact and irrelevant fact: zero of nine.", bridge: "Two courtesies also triggered the registered interpretation pause. The earlier runtime block left another question: what does the model choose, and what does the surrounding software allow?" },
  { id: "N-MACHINE-CAPABILITY", short: "Capability", experiment: "WEB-CAPABILITY-1A", question: "Was the mechanism the obstacle?", finding: "All eighteen visitors used the required mechanism, across six web interfaces. The predicted drop-off for code-requiring routes was refuted.", bridge: "The task supplied an address. The next experiment withheld it and tested how a provider enters an agent’s view." },
  { id: "N-MACHINE-DISCOVERY", short: "Exposure", experiment: "MACHINE-DISCOVERY-1", question: "Would the provider enter the agent’s view?", finding: "No withheld-address subject reached LLM Wilds. Every domain-supplied control completed the full funnel, while generic subjects found other providers.", bridge: "The failure was above selection in this search view. What external description makes a capability retrievable and recognisable as something an agent can use?" },
] as const;
