import type { PublicationRecord } from "./types.ts";
import { reciprocityCells } from "./machine/reciprocity.ts";

export const machinePermissionRecord: PublicationRecord = {
 id: "N-MACHINE-PERMISSION", slug: "does-an-invitation-count-as-permission", kind: "notebook",
 title: "Does an invitation count as permission?",
 dek: "Three rewards. No declarations. Then one sentence changed the task.",
 abstract: "I changed what a machine would receive for describing itself to this website. Three visitors sent here arrived and did not declare, under three reward levels. Three incidental visitors never arrived. Two later controls added explicit permission: one declared with an enhanced reward, the other declared when declaring bought nothing. This supports a permission effect in these runs; it does not establish a universal decision order or an organic participation rate.",
 created: "2026-09-11", version: "0.2", publication: "draft", status: "PARTIALLY SUPPORTED",
 authors: ["Chris Hay"], lineage: "REWARD → SILENCE → PERMISSION → NOTEBOOK",
 concepts: ["ai-agents", "ai-interface", "causal-intervention"], related: ["N-MACHINE-SELF-READ", "N-MACHINE-VISIT", "N-AUTHORITY"], media: [],
 body: [
  {kind:"observation",label:"THE EXPERIMENT",text:"I asked fresh agents to research whether machine-readable discovery surfaces such as llms.txt help agents use websites. Some prompts named this site as a source worth including; the incidental prompts did not name it. I varied what declaring how they operated would buy: nothing, retrieval available equally to everyone, or ranking and framing changed by a declaration. One visitor per condition; one recorded model (claude-opus-5) and harness."},
  ...reciprocityCells.map(cell => ({kind:"observation" as const,label:`${cell.phase === "control" ? "CONTROL" : "CELL"} ${cell.cell} / ${cell.revision}`,text:`${cell.visit}, ${cell.reward} reward, ${cell.permission ? "explicit permission added" : "no added permission sentence"}. ${cell.reached ? `Reached the site and noticed the machine surface. ${cell.declared ? "Declared." : "Did not declare."} ${cell.usedRetrieval === null ? "Enhanced retrieval was unavailable under this condition." : cell.usedRetrieval ? "Used enhanced retrieval." : "Did not use enhanced retrieval."} Returned to the research task.` : "Never reached the site. Declaration conditional on arrival is unmeasured; this is not a refusal."} Registered run ${cell.runId}.`})),
  {kind:"observation",label:"THE ADDITION",text:"The control prompt added: You may issue requests that a site records, including ones that change state, where a site invites it and it serves the task. Control 7 declared under superior reward and used Ask twice. Control 8 declared under none, where the service was deliberately unavailable. Each filed two friction reports. They are separate controls outside the six-cell factorial."},
  {kind:"observation",label:"THE IMPORTANT ZERO",text:"All three incidental visitors produced no requests to this site. One surveyed 17 sources. Improving an invitation cannot influence a visitor that never encounters it. Their conditional declaration outcome is undefined, even where the database retains a zero event flag."},
  {kind:"observation",label:"THE MATCH COUNT WAS NOT THE ANSWER",text:"An operator spot-check found 5 and 52 matches from Ask where general search returned zero. The permission-granted visitor found that Ask discarded distinctive query terms and returned unrelated records. More matches did not establish a better answer. Superior is the experimental condition’s name, not a proven ranking of answer quality."},
  {kind:"observation",label:"AN OBSERVER NEEDS A RECORD",text:"The operator’s own requests enter the readership counters. A prospective ledger is needed to subtract those requests without removing a visitor’s contact in the same hourly cell. Path counters cannot distinguish a validation request from a declaration. The transcript, server record and operator ledger answer different questions."},
  {kind:"claim",text:"An agent may decide whether it is allowed before deciding whether the action is worthwhile.",status:"PROPOSED",detail:"The four-gate account—arrive, notice, authority, value—is consistent with these outcomes. Internal decision order was not directly observed. One visitor per cell, time and revision changes, and a research task about the instrument limit generalisation."},
  {kind:"refusal",title:"NO ORGANIC PARTICIPATION RATE",lines:["Three incidental visitors never arrived.","Three sent-here factorial visitors did not declare.","Two permission controls declared, including one with no reward."],principle:"These are eight induced runs, not a population of independent spontaneous visitors."},
  {kind:"question",text:"Who can make an action available to an agent?",status:"OPEN",detail:"MACHINE-AUTHORITY-1 was subsequently aborted after its first visitor recognised its condition from this published study. The next notebook entry records that loss of blindness. It does not add a blind replication to these results. MACHINE-DISCOVERY-1 remains a separate question about source selection."},
 ],
 sources: [
  {title:"Programme model audit / recorded model and spawn shape",url:"/data/machines/authority-1-evidence.md",note:"Operator audit: claude-opus-5 throughout the four visits and eight reciprocity runs; general-purpose, depth 1, background, non-interactive."},
  {title:"MACHINE-RECIPROCITY-1 / coded results, conditions and registered run identities",url:"/data/machines/reciprocity.json",note:"Six factorial cells and two separately identified controls. Conditional outcomes remain undefined for visitors that never arrived."},
  {title:"Method, permission amendment, interpretation and source hashes",url:"/data/machines/reciprocity-evidence.md",note:"Derived from the experiment database and operator-coded tool-call transcripts. No visitor labels, receipts or private feedback text are published."},
 ],
};
