import { videoRecords } from "./video-records.ts";
import snapshots from "../content/publications.json" with { type: "json" };
import type { PublicationRecord } from "./types";
import { visualNotebooks } from "./visual-notebooks.ts";

export const SITE = "https://chrishayuk.com";
export const socials = { YouTube: "https://www.youtube.com/@chrishayuk", GitHub: "https://github.com/chrishayuk", LinkedIn: "https://www.linkedin.com/in/chrishayuk/", IBM: "https://www.ibm.com/think/podcasts/mixture-of-experts" };
const draft = { publication: "draft" as const, version: "0.1", authors: ["Chris Hay"], created: "2026-09-05" };
// These are reviewable editorial records. Publishing is a separate, explicit
// transition with a date and immutable snapshot; drafts never enter public feeds.
export const records: PublicationRecord[] = [
  { ...draft, id: "W-LARQL", slug: "larql", kind: "work", title: "LARQL", dek: "Models are places you can go.",
    abstract: "LARQL explores querying learned systems. This dossier connects the software to questions about model state, representations and what it means to make a model addressable.", status: "ONGOING", concepts: ["model-as-database", "model-representation"], related: ["W-VINDEX3", "N-CONTEXT", "Q-FFN"], media: ["larql-object"],
    body: [{ kind: "statement", text: "Models are places you can go." }, { kind: "question", text: "What if the structure inside a model could be queried?", status: "OPEN" }, { kind: "observation", label: "THE WORK", text: "LARQL is a software project for exploring learned systems. The question behind this record is how the model’s internal representations become something we can inspect, address and work with." }, { kind: "observation", label: "THE THREAD", text: "A model-as-database proposition connects this work to VINDEX3. The context notebook asks what becomes possible when earlier state can be returned to, rather than repeatedly reconstructed." }, { kind: "refusal", title: "NO BENCHMARK CLAIM HERE", lines: ["Record: software and an open line of inquiry", "Evidence: refer to the actual software and experiments"], principle: "A proposition is not a measured result." }],
    sources: [{ title: "LARQL software", url: "https://github.com/chrishayuk/larql" }, { title: "Homepage production brief", note: "Project proposition supplied by Chris Hay, September 2026." }] },
  { ...draft, id: "W-VINDEX3", slug: "vindex3", kind: "work", title: "VINDEX3", dek: "The model is the database.", abstract: "VINDEX3 is part of Chris Hay’s work on model representation. This dossier records the model-as-database proposition and links to the canonical project.", status: "ONGOING", concepts: ["model-as-database", "model-representation"], related: ["W-LARQL", "W-HAUSE"], media: ["vindex-system"],
    body: [{ kind: "statement", text: "The model is the database." }, { kind: "observation", label: "THE QUESTION", text: "What changes when a model is approached as structured, addressable material? The proposition directs attention to representation, the relationships between its parts, and execution." }, { kind: "comparison", objectLabel: "A model — a conceptual comparison", blockLabels: ["Structure", "Tensors", "Relations", "Provenance"], left: { label: "As a file", properties: ["An object to load", "Addressed from the outside"] }, right: { label: "As a database", properties: ["Parts to address", "Relationships to inspect"] } }, { kind: "observation", label: "READ THE SPECIFICATION", text: "The comparison is an explanation of the proposition, not a benchmark or an execution trace. The canonical project is the source for the representation and its technical contract." }],
    sources: [{ title: "VINDEX3 — canonical project", url: "https://vindex3.org/" }, { title: "Homepage production brief", note: "Project proposition supplied by Chris Hay." }] },
  { ...draft, id: "W-HAUSE", slug: "hause", kind: "work", title: "HAUSE", dek: "Meaning chooses its form.", abstract: "HAUSE is a semantic design system for AI interfaces: communicative acts rendered as statements, instruments and performances. This publication consumes its real components and publishing helpers.", status: "ONGOING", concepts: ["ai-interface", "semantic-design"], related: ["W-VINDEX3", "W-MCP"], media: [],
    body: [{ kind: "statement", text: "Structure is fixed. Atmosphere is variable." }, { kind: "observation", label: "THE WORK", text: "An assertion owes evidence. An open question deserves a visible status. A citation ties what is said to the record that says it. HAUSE gives these acts their own forms, rather than treating them as interchangeable boxes." }, { kind: "evidence", items: [{ label: "This site consumes the HAUSE source", status: "SUPPORTED", detail: "Package 0.1.0, source revision a93fb729c7d9ba02f7c1b2c369394526f9a3d158. The publication imports its Statement, Question, Claim, Evidence, Refusal, Comparison, Provenance and Citation forms." }] }, { kind: "observation", label: "THE EXHIBITION", text: "The publication adds its own photographic composition and coordinated media playback. The source library remains identifiable; the editorial direction belongs to Chris Hay." }],
    sources: [{ title: "HAUSE source", url: "https://github.com/chrishayuk/hause/tree/a93fb729c7d9ba02f7c1b2c369394526f9a3d158" }, { title: "The specimen book", url: "https://hause.design/" }] },
  { ...draft, id: "W-MCP", slug: "mcp-cli", kind: "work", title: "MCP-CLI", dek: "Machines using machines.", abstract: "MCP-CLI provides a command-line interface for working with Model Context Protocol servers. This dossier connects the interface to tool infrastructure and the wider CHUK work.", status: "ONGOING", concepts: ["mcp", "ai-interface"], related: ["W-HAUSE"], media: ["mcp-interaction"],
    body: [{ kind: "statement", text: "Machines using machines." }, { kind: "observation", label: "THE WORK", text: "MCP-CLI brings tool-connected interactions into a command-line interface. The project’s repository is the source for current installation instructions and supported providers, transports and commands." }, { kind: "observation", label: "CHUK", text: "The surrounding CHUK work includes tool processing, model interfaces and presentation. It is part of a broader investigation into how an agent’s actions can be explicit, inspectable and useful." }],
    sources: [{ title: "MCP-CLI source and documentation", url: "https://github.com/IBM/mcp-cli" }, { title: "CHUK projects", url: "https://github.com/chrishayuk" }] },
  { ...draft, id: "N-CONTEXT", slug: "context-should-be-abundant", kind: "notebook", title: "Context should be abundant.", dek: "What if context is expensive because we keep reconstructing it?", abstract: "An open notebook proposition: repeatedly reconstructing earlier state may be one reason context feels scarce. Indexing reusable state is a question to investigate, not an established saving.", created: "2026-08-26", status: "OPEN", concepts: ["context-engineering", "model-as-database"], related: ["W-LARQL", "W-VINDEX3"], media: ["operator-notebook"],
    body: [{ kind: "statement", text: "Context is treated as expensive because we repeatedly reconstruct it." }, { kind: "observation", text: "Every new call re-derives what a previous call already established, at real token cost, because nothing kept the earlier state in a form worth returning to. If that state were indexed rather than discarded, context stops being the scarce resource everyone budgets around." }, { kind: "question", text: "When does returning to state cost less than reconstructing it?", status: "OPEN", detail: "The notebook proposition needs measurements against a defined workload, including the cost of indexing and retrieval." }],
    sources: [{ title: "Chris Hay’s existing notebook source", note: "context-should-be-abundant.ts, recorded 26 August 2026. Imported as a draft; no historical publication date inferred." }] },
  { ...draft, id: "N-OPERATOR", slug: "the-operator-and-the-model", kind: "notebook", title: "The operator and the model.", dek: "Knowing where something goes is not the same as knowing what it does.", abstract: "An open thought distinguishing prediction of a model’s trajectory from reproducing its computation. It records a question; no experimental finding is asserted.", status: "OPEN", concepts: ["residual-stream", "recurrent-depth"], related: ["Q-RESIDUAL", "W-LARQL"], media: ["operator-notebook"],
    body: [{ kind: "statement", text: "The operator knows where the model goes. It doesn’t know what the model does." }, { kind: "question", text: "What would distinguish following a trajectory from reproducing the computation?", status: "OPEN", detail: "A useful experiment would compare both natural trajectories and responses to controlled changes. A result belongs in its own sourced record." }], sources: [{ title: "Homepage production brief", note: "Provisional thought supplied by Chris Hay. The illustrative N-0042 identifier and E25 findings have not been adopted as verified records." }] },
  { ...draft, id: "Q-FFN", slug: "ffn-as-graph", kind: "question", title: "What if the FFN is a graph?", dek: "An open question about the structure inside a model.", abstract: "Could a feed-forward network be usefully treated as an addressable graph? This question connects model representation to traversal and querying, without claiming an experimental answer.", status: "OPEN", concepts: ["ffn", "model-representation"], related: ["W-LARQL", "W-VINDEX3", "Q-RESIDUAL"], media: ["ffn-notebook"],
    body: [{ kind: "question", text: "What if the FFN is a graph?", status: "OPEN", detail: "The question is about whether the representation makes something useful possible: addressing, traversing or explaining the computation." }, { kind: "observation", label: "THE THREAD", text: "Start with the representation. Ask what can be addressed. Specify a traversal, then compare it with the original computation. Keep the distinction between an explanatory picture and an operational result." }, { kind: "refusal", title: "AN ANSWER IS STILL OPEN", lines: ["Question: addressable structure", "Required: reproducible experiments and explicit baselines"], principle: "A compelling representation must still earn its result." }], sources: [{ title: "Homepage production brief", note: "Open research question supplied by Chris Hay." }] },
  { ...draft, id: "Q-RESIDUAL", slug: "residual-geometry", kind: "question", title: "Can geometry predict the working set?", dek: "Observed together. Useful together?", abstract: "Does residual-stream geometry predict which parts of a model will be active or resident together? The existing research note records co-activation as observed and useful locality prediction as untested.", created: "2026-08-26", status: "OPEN", concepts: ["residual-stream", "mixture-of-experts"], related: ["W-LARQL", "N-OPERATOR"], media: [],
    body: [{ kind: "question", text: "Can residual geometry predict physical working-set behaviour?", status: "OPEN" }, { kind: "observation", label: "CURRENT POSITION", text: "The existing working note says co-activation has been observed, but has not been shown to predict anything useful. It records observing expert co-activation across related prompts on Kimi K3; locality prediction remains untested." }, { kind: "refusal", title: "PREDICTIVE LOCALITY IS NOT ESTABLISHED", lines: ["Recorded observation: expert co-activation", "Open question: useful physical working-set prediction"], principle: "Present is not the same as predictive." }], sources: [{ title: "Existing residual geometry question", note: "residual-geometry-question.ts, recorded 26 August 2026. This source is a working note, not a published experiment." }] },
];

const filmSources = [
  { id: "F-010", slug: "ai-hardware", title: "The material side of intelligence.", dek: "AI hardware, training, inference and model optimisation.", episode: "10", original: "ai-hardware-model-optimization", abstract: "Bryan Casey joins Volkmar Uhlig, Chris Hay and Kaoutar El Maghraoui for a discussion of AI hardware and model optimisation. An IBM Mixture of Experts episode.", concepts: ["model-representation", "ai-hardware"] },
  { id: "F-040", slug: "deepseek-facts-and-hype", title: "Between the facts and the hype.", dek: "DeepSeek, model distillation and open-source competition.", episode: "40", original: "deepseek-facts-vs-hype-model-distillation-open-source-competition", abstract: "Tim Hwang, Aaron Baughman, Chris Hay and Kate Soule discuss DeepSeek, distillation and competition in open models. An IBM Mixture of Experts episode.", concepts: ["mixture-of-experts", "open-models"] },
  { id: "F-046", slug: "manus-and-vibe-coding", title: "What happens after the prompt?", dek: "Manus, vibe coding, scaling laws and the AI phone.", episode: "46", original: "manus-vibe-coding-scaling-laws-perplexity-ai-phone", abstract: "Tim Hwang, Chris Hay, Kaoutar El Maghraoui and Vyoma Gajjar discuss Manus and agentic work, vibe coding, scaling laws and Perplexity’s AI phone. An IBM Mixture of Experts episode.", concepts: ["mcp", "ai-interface"] },
];
for (const f of filmSources) records.push({ ...draft, id: f.id, slug: f.slug, kind: "film", title: f.title, dek: f.dek, abstract: f.abstract, concepts: f.concepts, related: ["W-MCP", "W-LARQL"], media: ["moe-feature"], episode: f.episode, collection: "Mixture of Experts", originalUrl: `https://www.ibm.com/think/podcasts/mixture-of-experts/${f.original}`, sources: [{ title: `IBM — original episode ${f.episode}`, url: `https://www.ibm.com/think/podcasts/mixture-of-experts/${f.original}` }], body: [{ kind: "observation", label: "THE CONVERSATION", text: f.abstract }, { kind: "observation", label: "CREDITS", text: "Produced and published by IBM. Chris Hay appears as a participant. This is Chris Hay’s editorial record of the appearance; the original production and its rights remain with their respective owners." }] });

records.unshift(...visualNotebooks);
records.push(...videoRecords);

export type Snapshot = { record: PublicationRecord; hash: string; algorithm: "sha256" };
export const publicationSnapshots = snapshots as Snapshot[];
for (const snapshot of publicationSnapshots) {
 const i = records.findIndex(r => r.id === snapshot.record.id);
 if(i >= 0) records[i] = snapshot.record; else records.push(snapshot.record);
}
export const getVersion = (id: string, version: string) => publicationSnapshots.find(s => s.record.id === id && s.record.version === version);
export const sectionFor = (record: PublicationRecord) => record.kind === "question" ? "research" : record.kind;
export const recordPath = (record: PublicationRecord) => record.youtubeId ? `/film/youtube/${record.youtubeId}` : `/${sectionFor(record)}/${record.slug}`;
export const getRecord = (id: string) => records.find(r => r.id === id || r.slug === id);
export const publishedRecords = () => records.filter(r => r.publication === "published" && r.published);

export const indexedRecords = () => records.filter(r => r.publication === "catalogued" || (r.publication === "published" && r.published));
