import { readFile, writeFile } from "node:fs/promises";
import { getManuscript, type Snapshot } from "../lib/records.ts";
import { preparePublication } from "../lib/publication-release.ts";
import { compareVersions, type Provenance, type Revision } from "../vendor/hause/provenance.ts";
import { preserveEvidence } from "./publication-evidence.ts";

const [id, version, date, kind, summary] = process.argv.slice(2);
if (!id || !version || !date || !kind || !summary) throw new Error('Usage: node --experimental-strip-types scripts/publish-record.ts ID VERSION YYYY-MM-DD initial|clarification|interpretation|correction "What changed and why"');
const manuscript = getManuscript(id);
if (!manuscript) throw new Error("Unknown manuscript");
const path = new URL("../content/publications.json", import.meta.url);
const provenancePath = new URL("../content/publication-provenance.json", import.meta.url);
const previous: Snapshot[] = JSON.parse(await readFile(path, "utf8"));
const provenance: Provenance[] = JSON.parse(await readFile(provenancePath, "utf8"));
const predecessor = previous.filter(snapshot => snapshot.record.id === id).sort((a, b) => compareVersions(a.record.version, b.record.version)).at(-1);
const revision: Revision = { kind: kind as Revision["kind"], summary, ...(predecessor ? { previous: predecessor.record.version } : {}) };
const snapshot = preparePublication(manuscript, previous, version, date, revision);
if (provenance.some(entry => entry.id === id && entry.version === version)) throw new Error("Provenance already exists for this version.");
const sources = await preserveEvidence(snapshot.record.sources, new Date().toISOString().slice(0, 10));
provenance.push({ id, version, recordHash: snapshot.hash, revision, sources });
previous.push(snapshot);
await writeFile(provenancePath, JSON.stringify(provenance, null, 2) + "\n");
await writeFile(path, JSON.stringify(previous, null, 2) + "\n");
console.log(`Prepared ${id} v${version}: ${summary}. Review both manifests and preserved artifacts before deployment.`);
