import Link from "next/link";
import { pageMetadata } from "@/lib/metadata";
import { DEFINITIONS, NOTES, readershipReport, WINDOW_DAYS } from "@/lib/readership/report";
import { ContactField, ContactMap, EvidenceLegend } from "@/components/MachineEvidence";
import { contactHour } from "@/lib/readership/exhibit";
import { VISIT_PROTOCOL_PATH } from "@/lib/machine/visits";

export const metadata = pageMetadata("Machine readership — the observatory", "What machines encounter in this house. Hourly contact, content touched and the evidence behind each mark.", "/readership");
export const dynamic = "force-dynamic";

export default async function Page() {
 const report = await readershipReport();
 const field = report.counts?.exhibit;
 return <main id="main" className="publication-main machine-exhibition">
  <header className="index-intro me-intro"><p className="kicker record-voice">CHRIS HAY / READERSHIP / THE OBSERVATORY</p><h1>What arrives<br/><em>at the house.</em></h1><p className="dek">Machines encounter this publication in different ways. Follow the contact through time, then open a mark to see what the site actually knows.</p></header>
  <section className="me-room me-field" aria-labelledby="contact-heading"><div className="me-section-head"><h2 id="contact-heading">A field of encounters.</h2><p className="record-voice">48 HOURS · HOURLY COUNTERS · UTC</p></div><EvidenceLegend/>
   {field ? <ContactField exhibit={field}/> : <p className="me-empty">{report.recording ? "The readership store is unavailable. No observations can be shown." : "This deployment keeps no readership counters. The field is empty, without invented visitors."}</p>}
   <p className="me-caption">Requests, not visits. A mark records contact, not comprehension. This field includes operator activity; the store does not label a request’s origin as organic or induced.</p>
  </section>
  <section className="me-room" aria-labelledby="map-heading"><div className="me-section-head"><h2 id="map-heading">Which parts they touch.</h2><p className="record-voice">LAST {WINDOW_DAYS} DAYS · PUBLISHED PATHS · ASSETS EXCLUDED</p></div>{field ? <ContactMap exhibit={field}/> : <p className="me-empty">The contact map appears when retained observations are available.</p>}<p className="me-caption">Paths are alphabetical, not ranked by popularity. Refuted claims are excluded. Served content revisions were not retained, so this map cannot yet establish which version of an idea entered circulation.</p></section>
  <section className="me-room me-reconciliation" aria-labelledby="reconcile-heading"><div className="me-section-head"><h2 id="reconcile-heading">The observer leaves marks.</h2><p className="record-voice">KNOWN OPERATOR REQUESTS / 10 SEP 2026</p></div><p>Checks made by this site appear in its own counters. The ledger names eleven requests in three cells. Each subtraction below applies only to its matching cell.</p>
   {field ? field.corrections.map((row, i) => <details key={i} className="me-correction"><summary><span>{row.reason}</span><span>{row.observed === null ? "Outside report window" : row.remaining === null ? "Unresolved cell" : `${row.observed} − ${row.n} = ${row.remaining}`}</span></summary><div className="me-reconcile-bars"><div><span>Observed in cell</span><i style={{ width: "100%" }}/><b>{row.observed ?? "—"}</b></div><div><span>Known instrumentation</span><i style={{ width: row.observed ? `${Math.min(100, row.n / row.observed * 100)}%` : "0%" }}/><b>−{row.n}</b></div><div><span>Remaining unattributed</span><i style={{ width: row.observed && row.remaining !== null ? `${row.remaining / row.observed * 100}%` : "0%" }}/><b>{row.remaining ?? "—"}</b></div></div><p><code>{contactHour(row.hour)} /machines · page · automation · unknown · {row.agent} · inferred · none</code></p><p className="me-caption">{row.remaining === null ? "The retained cell cannot support this subtraction. No corrected total is asserted." : "Other traffic in the same hour remains counted. A remainder is not proof of organic traffic."}</p></details>) : <p className="me-empty">The three ledger corrections are documented; their live cells are unavailable on this deployment.</p>}
   <p className="me-caption">The field above shows observed contact before operator subtraction. This manual ledger is incomplete; it does not cover every blind-run request. <a href="/data/machines/operator-corrections.md">Inspect the correction source ↗</a></p>
  </section>
  <section className="me-room me-next"><p className="record-voice">FROM CONTACT TO BEHAVIOUR</p><h2>Send a visitor.<br/><em>Change the environment.</em></h2><p>Four blind runs tested whether a machine could find the invitation and use it. Their paths belong to an experiment, not a population count.</p><Link className="text-link" href={VISIT_PROTOCOL_PATH}>MACHINE-VISIT-1 / OPEN THE EXPERIMENT ↗</Link><Link className="text-link" href="/machine-guestbook">THE GUESTBOOK / COARSE PRESENCE ↗</Link></section>
  <section className="me-room"><details className="me-method"><summary>How this observatory measures</summary>{NOTES.map(note => <p key={note}>{note}</p>)}<p>The field covers {field ? `${contactHour(field.from)} to ${contactHour(field.to)} (end exclusive)` : "the latest 48 hourly buckets"}. The map covers {report.window.from ?? "the retained window"} to {report.window.to ?? "now"}. Hidden paths and assets do not appear in either visualization.</p><p>Verification snapshot: {report.verification.retrievedAt}. Hourly counters are retained for {report.retentionDays} days. Refuted requests in the report window: {report.counts?.confidence.refuted ?? "unavailable"}.</p><dl>{Object.entries(DEFINITIONS).map(([key, definition]) => <div key={key}><dt>{key.replaceAll("_", " ")}</dt><dd>{definition}</dd></div>)}</dl><Link className="text-link" href="/api/readership">THE SAME EVIDENCE AS JSON ↗</Link></details></section>
 </main>;
}
